### ISSUE TITLE
Exposed old (not latest) PMA interface with setup

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/website#38]
As report by Emanuel Bronshtein,

https://admin.phpmyadmin.net/phpmyadmin/
Running PMA version: phpMyAdmin 4.2.12deb2+deb8u2
Version detected via SETUP export, see issue: https://github.com/phpmyadmin/phpmyadmin/issues/12469
 
fix:
    1. upgrade to latest PMA version. (may require upload to debian-stable? so might wait for 4.6.5?)
    2. it's better to change the folder to not-predictable name / set BF protection (Recaptcha)
    3. disable exposing setup: https://admin.phpmyadmin.net/phpmyadmin/setup/

**Comment by nijel** [comment]
Okay, we should really follow best practices on our own server :-).

**Comment by nijel** [comment]
Okay, I've changed setup:

- Setup and libraries are no longer exposed at all.
- I've fixed the PHP setup as this site was dead since upgrade to PHP 7.
- The phpMyAdmin is now available only on request and has to be enabled on the server.

The reason is that I don't think anybody uses this regularly (at least nobody did notice it's broken for few weeks).
